In [2]:
import torch
import torch.nn as nn

In [3]:
model = nn.Linear(in_features=2,out_features=1)

x = torch.tensor([1.0,2.4])
y = model(x)
y

tensor([0.3208], grad_fn=<ViewBackward0>)

## Let’s Inspect the Weights & Bias (Curiosity time 👀)

In [4]:
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0854, -0.0864]], requires_grad=True)
Parameter containing:
tensor([0.6135], requires_grad=True)
